### ISSUE TITLE
setup.py fails to run

### ISSUE THREAD

**Issue by jsyeo** [uber/hacheck#38]
I am getting this error whenever I execute `python setup.py`:

```
Traceback (most recent call last):
  File "setup.py", line 26, in <module>
    install_requires, dependency_links = get_install_requirements()
  File "setup.py", line 17, in get_install_requirements
    for ir in parse_requirements('requirements.txt', options=opts):
  File "/home/j/repos/hacheck/env/local/lib/python2.7/site-packages/pip/req/req_file.py", line 78, in parse_requirements
    "parse_requirements() missing 1 required keyword argument: "
TypeError: parse_requirements() missing 1 required keyword argument: 'session'
```

**Comment by jsyeo** [comment]
Related commit in PIP: https://github.com/pypa/pip/commit/7037443975ee5706ef829f14a52ac2fba7dbfff2

**Comment by craig** [comment]
Hello, is uber going to fix this, or did they stop using it? Or did they not push their fixes to github? Should we use Yelp's fork https://github.com/Yelp/hacheck instead?
